spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/growith
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: asdf1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true